//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netio_Sample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Netio_Sample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;1&lt;/ID&gt;
        ///   &lt;Action&gt;0&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_1_OFF {
            get {
                return ResourceManager.GetString("OutPut_1_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;1&lt;/ID&gt;
        ///   &lt;Action&gt;1&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_1_ON {
            get {
                return ResourceManager.GetString("OutPut_1_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;2&lt;/ID&gt;
        ///   &lt;Action&gt;0&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_2_OFF {
            get {
                return ResourceManager.GetString("OutPut_2_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;2&lt;/ID&gt;
        ///   &lt;Action&gt;1&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_2_ON {
            get {
                return ResourceManager.GetString("OutPut_2_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;3&lt;/ID&gt;
        ///   &lt;Action&gt;0&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_3_OFF {
            get {
                return ResourceManager.GetString("OutPut_3_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;3&lt;/ID&gt;
        ///   &lt;Action&gt;1&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_3_ON {
            get {
                return ResourceManager.GetString("OutPut_3_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;4&lt;/ID&gt;
        ///   &lt;Action&gt;0&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_4_OFF {
            get {
                return ResourceManager.GetString("OutPut_4_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;set:Root xmlns:set=&quot;http://www.netio-products.com/XMLSchema/NETIO.xsd&quot;&gt;
        /// &lt;Outputs&gt;
        ///  &lt;Output&gt;
        ///   &lt;ID&gt;4&lt;/ID&gt;
        ///   &lt;Action&gt;1&lt;/Action&gt;
        ///  &lt;/Output&gt;
        /// &lt;/Outputs&gt;
        ///&lt;/set:Root&gt;
        ///.
        /// </summary>
        internal static string OutPut_4_ON {
            get {
                return ResourceManager.GetString("OutPut_4_ON", resourceCulture);
            }
        }
    }
}
